### ISSUE TITLE
Darkmode tabs

### ISSUE THREAD

**Issue by GrosBourrin** [themoonmeetsthesun/silentfox#2]
i see on the pics a little issue with the left and right down corners

![darkmode](https://user-images.githubusercontent.com/40931468/163441577-35458a84-0700-45da-9871-d6ce07e5b070.png)

**Comment by themoonmeetsthesun** [comment]
> i see on the pics a little issue with the left and right down corners
> 
> ![darkmode](https://user-images.githubusercontent.com/40931468/163441577-35458a84-0700-45da-9871-d6ce07e5b070.png)

I am aware of that, if you have a pull request I will surely merge it. I am not getting time to fix the issues. The guy who made the original project did not maintain it anymore which left bugs and visual glitches.

**Comment by themoonmeetsthesun** [comment]
Plus I am not so great with CSS

**Comment by themoonmeetsthesun** [comment]
![image](https://user-images.githubusercontent.com/96462198/164933790-6af582b9-641e-4eef-9bbc-7b2cbc8a86f5.png)
Fixed, now check

**Comment by GrosBourrin** [comment]
nice done

**Comment by themoonmeetsthesun** [comment]
> nice done

I just removed and turned off some code 😅
